name: pre-commit-uv
description: run pre-commit with pre-commit-uv
inputs:
  install:
    description: '"uv pip install ..." before running pre-commit, for local hooks'
    required: false
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v5.1.0
      with:
        cache-dependency-glob: ".github/workflows/*.yml"
        cache-suffix: pre-commit-uv
    - run: uv tool install pre-commit --with pre-commit-uv --force-reinstall
      shell: bash
    - run: uv pip install ${{ inputs.install }}
      shell: bash
      if: ${{ inputs.install }}
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-uv-v1-${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pre-commit run --all-files --show-diff-on-failure --color=always
      shell: bash
